from time import sleep
from colorama import init
from colorama import Back
from colorama import Style
from colorama import Fore
import os
clear=lambda: os.system('cls')
init()
a=0
while a<1:
	clear()
	print('Happy birthday, daddy!!!')
	print(' ')
	print('                     ..-..')
	print('     × * × * ×      (     )     ')
	print('    _|_|_|_|_|_     \     /      ')
	print('  _|___________|_    \___/')
	print(' _|_____________|_     |')
	print('|_________________|    |')
	print('HAPPY BIRTHDAY!')
	print(' ')
	print(Fore.BLUE)
	sleep(0.35)
	clear()
	print('Happy birthday, daddy!!!')
	print('                     ..-..')
	print('                    (     )')
	print('     * * * * *      \     / ')
	print('    _|_|_|_|_|_      \___/     ')
	print('  _|___________|_      |')
	print(' _|_____________|_     |')
	print('|_________________| ')
	print('HAPPY BIRTHDAY!')
	print(Fore.RED)
	print(Fore.YELLOW)
	sleep(0.35)
	clear()
	print('Happy birthday, daddy!!!')
	print(' ')
	print('                     ..-..')
	print('     * × * × *      (     )     ')
	print('    _|_|_|_|_|_     \     /      ')
	print('  _|___________|_    \___/')
	print(' _|_____________|_     |')
	print('|_________________|    |')
	print(' ')
	print('HAPPY BIRTHDAY!')
	print(Fore.RED)
	sleep(0.35)
